# Generated by Django 4.1.6 on 2023-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pench', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
