# Generated by Django 4.1.6 on 2023-02-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pench', '0003_alter_file_name_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pench.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pench.folder'),
        ),
    ]
