# Generated by Django 4.1.6 on 2023-02-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pench', '0004_folder_location_alter_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
