# Generated by Django 4.1.6 on 2023-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pench', '0005_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=100000, upload_to='data/'),
        ),
    ]
